language: python
sudo: false
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=pypy
notifications:
  irc: "chat.freenode.net#redislite"
matrix:
  fast_finish: true
  allow_failures:
    - env:
      - TOX_ENV=pypy
      - TOX_ENV=build_docs
install:
  - pip install --upgrade pip setuptools tox virtualenv coveralls
script:
  - tox -v -v -e $TOX_ENV
after_success:
  coveralls
after_failure:
  - for X in .tox/$TOX_ENV/log/*; do echo "$X\n"; cat "$X"; echo "\n\n"; done
  - echo "pip.log\n"; cat $HOME/.pip/pip.log
